name: Android Tests with Coverage Check and Coveralls

on:
  push:
    branches:
      - '**'  
  pull_request:
    branches:
      - 'main'
      - 'master'
      - 'develop'
      - 'release/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Run tests and generate coverage report
      run: ./gradlew test jacocoTestReport
    
    - name: Check coverage
      run: |
        COVERAGE=$(grep -oP 'Total.*?([0-9]{1,3})%' app/build/reports/jacoco/jacocoTestReport/html/index.html | grep -oP '[0-9]{1,3}')
        if (( $(echo "$COVERAGE < 70" | bc -l) )); then
          echo "Coverage is below 70%: $COVERAGE%"
          exit 1
        else
          echo "Coverage is $COVERAGE%"
        fi

    - name: Upload coverage data to coveralls.io
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml
        base-path: app/src/main/java

  coveralls:
    name: Indicate completion to coveralls.io
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel-finished: true